### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by gowthamk17** [nt4f04uNd/sweyer#15]
App crashes  when open android 10, app version latest 1.0.4

**Comment by nt4f04uNd** [comment]
Would you mind to share your phone model please?

**Comment by nt4f04uNd** [comment]
You can try 1.0.5 https://github.com/nt4f04uNd/sweyer/releases/tag/1.0.5

The supposed crash happened, because the art for some song on your device couldn't be loaded. I can't tell exactly without your phone model

**Comment by gowthamk17** [comment]
realme 3

**Comment by gowthamk17** [comment]
> You can try 1.0.5 https://github.com/nt4f04uNd/sweyer/releases/tag/1.0.5
> 
> The supposed crash happened, because the art for some song on your device couldn't be loaded. I can't tell exactly without your phone model

this version works,  that last version after granted the permission the app just crashed,
