### ISSUE TITLE
Localisation difficulties

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#23]
Currently it is not possible to add a localisation in a way that all translated text is displayed correctly for the new language.
There are two problems:
1. The current code base forces some text to always be lower case. This causes problems for languages which use uppercase letters, e.g. German where a noun must be capitalized: (Wrong: `1 lied`, Correct: `1 Lied`) 
2. In some places multiple parts of a sentence are pieced together in code, making it impossible to be changed in the language file to adjust it for the language. A prime example is `areYouSureYouWantTo`, where the action is added at the end. This won't work for all languages.

A reason for this current state is that many strings can be reused this way in English, but it takes away the flexibility needed for translation. As an example, currently we have the following situation:

| Key                    | English                                                                                                                                          |
|------------------|-------------------------------------------------------------------------------------------------------|
| `delete`             | `Delete`                                                                                                                                          |
| `tracksPlural`    | `{count,plural, =0{Tracks}=1{Track}=2{Tracks}few{Tracks}many{Tracks}other{Tracks}}`                   |
| `playlistsPlural` | `{count,plural, =0{Playlists}=1{Playlist}=2{Playlists}few{Playlists}many{Playlists}other{Playlists}}` |

These are combined in https://github.com/nt4f04uNd/sweyer/blob/5e18cda1a292cb7deb04c5587604c4b4c32ad331/lib/widgets/selection.dart#L1849

The only solution I can see is to create specialized versions of all strings. We would have to keeping the original ones, if they are used somewhere else. In the example above, we would end up with:

| Key                     | English                                                                                                                                          |
|-------------------|-------------------------------------------------------------------------------------------------------|
| `delete`              | `Delete`                                                                                                                                          |
| `tracksPlural`     | `{count,plural, =0{Tracks}=1{Track}=2{Tracks}few{Tracks}many{Tracks}other{Tracks}}`                   |
| `playlistsPlural`  | `{count,plural, =0{Playlists}=1{Playlist}=2{Playlists}few{Playlists}many{Playlists}other{Playlists}}` |
| `deleteTracks`    | `{count, plural, =1{Delete track} other{Delete {count} tracks}}`                                                     |
| `deletePlaylists` | `{count, plural, =1{Delete playlist} other{Delete {count} playlists}}`                                              |

This way, the translator can change the case and positioning of everything.

Do you see any better alternative? I'm willing to put in some time to change this, if you approve.

**Comment by nt4f04uNd** [comment]
I agree that building those strings inside the app's logic wasn't a very good choice.

Sure, adding new strings for each case where this is needed sounds good to me, feel free to submit a PR. I have just created a new branch for work on the next version, so please target your PR into this branch https://github.com/nt4f04uNd/sweyer/tree/1.0.8

**Comment by nt4f04uNd** [comment]
Also FYI I'm not using dart formatter in this repository :-)

**Comment by Abestanis** [comment]
>  feel free to submit a PR.

Will do. 👍 

> Also FYI I'm not using dart formatter in this repository :-)

Having a consistent coding style would be nice, since I'm not familiar with your coding style and I think mixing two styles haphazardly would't look very great. The changes required for this should all be relatively small, I will try to use the style of the existing code. But it might be beneficial to define a format style and reformat everything at some point in the future, so we can use the auto-formatting capabilities of our IDE.

**Comment by nt4f04uNd** [comment]
Mainly, the repo has a set of lints in [analysis_options](https://github.com/nt4f04uNd/sweyer/blob/master/analysis_options.yaml) that enfore the style that I'm following, so just following them and the code that you see around you should be fine. It's possible that I will switch to `flutter_lints` soon.

The coding style is very similar (but not exactly the same) what Flutter framework itself uses, and the set of lints was created by copying and redacting Flutter's [analysis_options](https://github.com/flutter/flutter/blob/master/analysis_options.yaml). You can read it here, if you are interested https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo - in particular, it includes not using auto formatter.

I agree that I should explore using auto formatter, and I'm now thinking of just using default dart formatter, but extending its default line break threshold from 80 to 120 - it seems to work fine most of the time, just needs a little petting.
