### ISSUE TITLE
☂ 1.0.8 version discussion

### ISSUE THREAD

**Issue by nt4f04uNd** [nt4f04uNd/sweyer#38]
A place for a general discussion about developing the new version.
I also created a project to better keep track of what is being done.

cc @Abestanis feel free to write any other plans that you have,
you have been contributing a lot recently, don't forget to take a rest :-)

**Comment by Abestanis** [comment]
I wanted to focus on fixing some small issues I noticed while using the app, and then focus on adding a home screen widget.
I'm going to create issues for the small problems, some of them should probably be fixed before the release. I wouldn't block the release on the home screen widget, it can also be in the next release.

**Comment by nt4f04uNd** [comment]
Cool, sounds good to me.

Also, regarding the home widget, I'd say that there are no existing good enough solutions that would allow to use Flutter, AFAIK. So likely, this would involve writing this widget natively and then using platform channels to communicated with the app's business logic. But it's still worth exploring what kind of solutions exist, since I didn't look really close at it.

**Comment by nt4f04uNd** [comment]
@Abestanis let's pause and land what we already have in a list of pull requests, so I can make full Flutter 3 migration and set up auto formatting without it causing an enourmous amount of merge conflicts. Hopefully, I will get to the rest of the pull requests on this weekend.

**Comment by Abestanis** [comment]
Sounds good, thank you for all the reviews! There is no need to hurry.

**Comment by nt4f04uNd** [comment]
@Abestanis Flutter 3 migration and auto formatting (https://github.com/nt4f04uNd/sweyer/pull/61) has now been merged

**Comment by nt4f04uNd** [comment]
@Abestanis hey, I have some good news here - I finally sent the 1.0.8 to Google Store review and merged the branch with master. I will make a GitHub release after it gets approved and published.

I made the required changes to publish an app updated - which is bumping `targetSdkVersion` to 33.

I also updated the CHANGELOG, recollecting most of the changes we made in this version, and left a thank you to you in the README!

It was a great pleasure to accept all of your wonderful contributions!
Thank you! ❤️

**Comment by Abestanis** [comment]
Hey, awesome, I'm looking forward to getting the update!

Thank you for starting this and still putting effort into this project. It was and still is a great pleasure working together with you on this.
I've been using Sweyer as my music player on my phone for the past year, and I am very happy with it!
And thank you for the mention in the README, I really appreciate it! ❤️
