### ISSUE TITLE
Empty space at the bottom of the artist route

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#40]
I'm not entirely sure if this is a bug or a feature, but there is a big empty space at the bottom of the artist route, when you scroll down:
<details>
<summary>Screenshot</summary>

![Artist page with empty space](https://user-images.githubusercontent.com/6966049/169141035-532445cc-f9dd-4e19-9ba8-dbd6cf3bfe55.png)
</details>

Is the space intentional? It felt a bit off to me.

**Comment by Abestanis** [comment]
I just noticed the playlist detail screen has the same issue.

**Comment by nt4f04uNd** [comment]
This is intended and there's a code that specifically does that. Don't ask why, I just like this.

https://github.com/nt4f04uNd/sweyer/blob/ca3eadcfaaebb6db110a65ee73ed805115b85e11/lib/routes/home_route/artist_route.dart#L280-L289
