### ISSUE TITLE
The shuffle button doesn't visually update

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#46]
The shuffle button in the player route doesn't indicate, whether shuffling is currently enabled or not:

![Shuffle button problem demonstration](https://user-images.githubusercontent.com/6966049/169152871-129ff98b-8955-4774-ae6e-0693b235988f.gif)

**Comment by nt4f04uNd** [comment]
Will be fixed in https://github.com/nt4f04uNd/sweyer/pull/34
