### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#53]
### Steps to reproduce

1. Play a song.
2. Close the app.
3. Open the app.
4. Observe error in Logcat log.

### What did you expect?

No error on startup.

### What happened instead?

The following error is thrown:
```dart
----------------FIREBASE CRASHLYTICS----------------
I/flutter (16104): Null check operator used on a null value
I/flutter (16104): #0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:139:49)
I/flutter (16104): #1      _QueueTabState.scrollToSong (package:sweyer/routes/home_route/player_route.dart:236:43)
I/flutter (16104): #2      _QueueTabState.initState.<anonymous closure> (package:sweyer/routes/home_route/player_route.dart:216:15)
I/flutter (16104): #3      _QueueTabState.initState.<anonymous closure> (package:sweyer/routes/home_route/player_route.dart:210:76)
I/flutter (16104): #4      _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter (16104): #5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter (16104): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter (16104): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
I/flutter (16104): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter (16104): #9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
I/flutter (16104): #10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
I/flutter (16104): #11     _StartWithStreamSink._safeAddFirstEvent (package:rxdart/src/t
```

A simple fix would be to check `scrollController.position.hasContentDimensions` before, but I'm wondering if this is maybe just the symptom of an inverted if condition here:
https://github.com/nt4f04uNd/sweyer/blob/93b5bdf053faed2ceae459f07f7bb85b56273fb2/lib/routes/home_route/player_route.dart#L214-L217

I have two questions about this, @nt4f04uNd:
Was the intention of this to scroll to the currently playing song in the queue view when the user is looking at it?
1. If yes, is that really what we want? I would find that very annoying, if I'm just browsing through the queue and would get scrolled to the currently playing song when it changes. How do you feel about a setting to control this behavior?
2. If no, why wouldn't we just jump to the new song item? Since it is offsceen, there is no need for scrolling.

### Sweyer version

Latest on the `1.0.8` branch; 93b5bdf053faed2ceae459f07f7bb85b56273fb2

**Comment by nt4f04uNd** [comment]
The intention was to scroll it for closely located tracks (the animation can be seen when switching a track and then immediately opening the queue route) and jump for far located tracks.

I don't really understand why we started catching this only now, but this should just be post-framed.

**Comment by nt4f04uNd** [comment]
Oh wow, it might be harder than I thought

**Comment by nt4f04uNd** [comment]
Actually, I just forgot about the `mounted` check.
