### ISSUE TITLE
Layout issues when increasing the system font size

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#66]
### Steps to reproduce

1. Increase the system font size in the Android settings. (Anything that causes a `MediaQuery.textScaleFactor >= 1.1`)
2. Open the app.

### What did you expect?

There should be no layout issues.

### What happened instead?

The height given for the `SongTitle` widget is not enough to contain the two lines of text. This is because `kSongTileHeight` doesn't take the `textScaleFactor` into account.

Additionally, the tab header widget on the bottom is partially hidden behind the bottom sheet.

![Layout issues on higher textscale settings](https://user-images.githubusercontent.com/6966049/174410710-1222a1f1-25d9-482a-9ed1-673f7cd73567.png)

For context, the default font size setting on my phone produces a `textScaleFactor` of `1.1`. The old version of Sweyer (`1.0.7`) does not have this problem.

### Sweyer version

Latest on the `1.0.8` branch; 4460b5a9688edcfd4ac32e3f3530c22d0d0cdca9

**Comment by nt4f04uNd** [comment]
We need to report this bug to `styled_text`: when using a `Text.rich` with `WidgetSpan` with `StyledText` as a child, and both Text.rich and StyledText have a text `style`, the `textScaleFactor` scales the text twice as much, unless we explicitly specify `textScaleFactor = 1.0` on either of them.

I don't have time right now to make this into a detailed issue with a reproducible code sample - so leaving a comment here to come back to doing this later.

**Comment by nt4f04uNd** [comment]
https://github.com/andyduke/styled_text_package/issues/83 opened and issue and passed it to TODOs in code

Finally closing this issue
