### ISSUE TITLE
Sweyer no longer has access to music

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#83]
### Steps to reproduce

1. Open the newest 1.0.8 version on a phone with Android 13
2. The app is not asking to grant storage permissions and the app shows that there is no music on my phone.
3. Deleted the app data and cache and opened it again.
4. This time the app askes to grant storage permissions.
5. The user is redirected to the settings page to grant the permission manually, but there is no option to grant any permission. The settings app shows that the app does not require any permission.

### What did you expect?

To see music and to be able to grant the app access to it.

### What happened instead?

The app does not have access to the music.

### Sweyer version

1.0.8

### Android version

Android 13

**Comment by Abestanis** [comment]
This might be a problem of the new target API level and Android 13 [granular media permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), I'm investigating.

**Comment by nt4f04uNd** [comment]
I'm assuming that https://developer.android.com/about/versions/13/behavior-changes-13#ux also could have affect the app notification.

I also saw that audio_service has some issue with a PR about it https://github.com/ryanheise/audio_service/issues/972

Will go through the entire list of changes later.

**Comment by Abestanis** [comment]
> [...] could have affect the app notification.

Yeah, this is API level 24 and it looks like the stop and shuffle buttons are no longer visible:
![Music notification](https://user-images.githubusercontent.com/6966049/230745934-3e7ea82e-cf38-4fd9-87c4-81f40c80f366.png)
Everything else still seems to work though.
