### ISSUE TITLE
Use drag position instead of scrollbar thumb to determine whether to show labels

### ISSUE THREAD

**Issue by Abestanis** [nt4f04uNd/sweyer#88]
### Suggestion

When the user drags the scroll bar of the content lists (Tracks, Albums, Playlists and Artists) we show a label if the sorting is set to name or title.

![Scroll label](https://user-images.githubusercontent.com/6966049/235318925-9688bc83-db0a-4444-be8f-4cbc0f40b563.png)

This is a cool feature, but it is very hard to get to, because the scroll bar is only a few pixels wide. Additionally, to provide this feature we are keeping a copy of the Scrollbar code from Flutter, which requires us to manually keep it up to date with the Flutter implementation to get improvements and to keep compatible with changes in the framework.

I want to get your feedback on an alternative solution to this problem that does not require us to keep a slightly modified version of the code and makes the feature easier to access:

Instead of only showing the label when the scrollbar is dragged, show it when a scrolling from a drag, while the touchpoint of the drag is close to the window border on the scrollbar side. For the picture above, this would mean when dragging the list close to the right side of the screen, the labels would show up.

We can implement this using a `NotificationListener<ScrollNotification>` and the `dragDetails?.localPosition` of `ScrollStartNotification` & `ScrollUpdateNotification`.

I would like to implement this, if you are ok with it, @nt4f04uNd.

**Comment by nt4f04uNd** [comment]
Hi, this sounds like a great addition 😊👍

This is definitely something I thought about at some point in the past, but there were  no existing solutions, IIRC.

It looks like we could possibly use https://pub.dev/packages/alphabet_scroll_view to achieve that effect, are you going to use this?

From one hand - it's good we have some package do it for us, on the other hand, we're adding one more dependency, and the ListView component is very core to a framework by its nature, so we have to make sure this solution is executed well enough to not bury a long shot to our leg in the future.

Ideally, this should work without swapping out our ListViews by some other widget, and if you can achieve this, I'm definitely for it.

**Comment by nt4f04uNd** [comment]
> Additionally, to provide this feature we are keeping a copy of the Scrollbar code from Flutter, which requires us to manually keep it up to date with the Flutter implementation to get improvements and to keep compatible with changes in the framework.

I don't think these two thing are related though. It is unfortunate that I didn't leave a comment as to why I copied it over, but I'm pretty sure it's something related to the color of the scrollbar.

**Comment by nt4f04uNd** [comment]
Ah, it's onThumbPressStart and onThumbPressEnd handles, I see. You are right.

**Comment by Abestanis** [comment]
> Ah, it's onThumbPressStart and onThumbPressEnd handles, I see. You are right.

Yes exactly. Sorry, I should have mentioned that. I think I can do it with just a `NotificationListener`, no extra package needed.
