### ISSUE TITLE
Codecov webhook 403

### ISSUE THREAD

**Issue by nt4f04uNd** [nt4f04uNd/sweyer#92]
It seems like Codecov itself is working correctly
https://app.codecov.io/gh/nt4f04uNd/sweyer/tree/master/lib/logic

But I the repo settings, under a `Webhooks` section I found that there's some webhook, which I didn't create and it is somehow related to the Codecov.

https://github.com/nt4f04uNd/sweyer/settings/hooks/357895302

It calls into `https://codecov.io/webhooks/github`, but all of the responses are just 403

<details><summary>Details</summary>
<p>

<img width="790" alt="Снимок экрана 2023-05-01 в 17 52 06" src="https://user-images.githubusercontent.com/39104740/235448064-5d58bab0-68ce-4239-9f83-5351b04d9b4a.png">

</p>
</details>

**Comment by nt4f04uNd** [comment]
@Abestanis do you know what is this?

**Comment by Abestanis** [comment]
Hm, I'm not sure about the webhook. I don't have access to the webhook configuration, so I don't think it was me who added it. Maybe the GitHub action creates it somehow automatically?

I would just deactivate it and see if anything breaks. If not, remove it.

**Comment by nt4f04uNd** [comment]
Deleted the hook, seems like nothing broke. Closing.
